### ISSUE TITLE
page not working in Example

### ISSUE THREAD

**Issue by BasimYHammad** [tamara-solution/ios-sdk#5]
When you try to run the page example, appear empty and white page

log :
filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}

but if copy link and open in Safari its working 
![WhatsApp Image 2021-04-18 at 6 41 41 PM](https://user-images.githubusercontent.com/36499957/115525253-96e0ac00-a297-11eb-882f-5b670a84f009.jpeg)

**Comment by thanhpham22** [comment]
`self.appState.viewModel = TamaraSDKCheckoutViewModel(url: item.checkoutUrl, merchantURL: merchantUrl, webView: nil)`
